"""empty message

Revision ID: 3072406ff55c
Revises: 
Create Date: 2020-11-10 14:38:08.867649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3072406ff55c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_team', sa.String(length=30), nullable=True),
    sa.Column('guest_team', sa.String(length=30), nullable=True),
    sa.Column('home_points', sa.String(length=3), nullable=True),
    sa.Column('guest_points', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('acronym', sa.String(length=10), nullable=True),
    sa.Column('local', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_acronym'), 'teams', ['acronym'], unique=True)
    op.create_index(op.f('ix_teams_local'), 'teams', ['local'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_local'), table_name='teams')
    op.drop_index(op.f('ix_teams_acronym'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('matches')
    # ### end Alembic commands ###
